Feature/rishabh/2 11 2021/UI changes
meharajM/mpp-v1 pull request #12
Opened 2021-11-19 14:51 UTC by Ri5ha6h

2021-11-20 16:07 UTC, meharajM requested changes

2021-11-20 16:07 UTC, meharajM commented on app/containers/Dashboard/index.js
> +import './styles.scss';
move all styles of this file from style prop to styles.scss file

2021-11-20 16:07 UTC, meharajM commented on app/containers/Dashboard/index.js
> +                                    style={{
put all the repeated style code in a const and use it

2021-11-20 16:07 UTC, meharajM commented on app/containers/Dashboard/index.js
> +                              marginLeft: 5,
put all the repeated style code in a const and use it, or put it in styles.scss file with a class name and use it

2021-11-20 16:07 UTC, meharajM commented on app/containers/Profile/index.js
> +                style={{
move style to styles.scss

2021-11-20 16:07 UTC, meharajM commented on app/containers/SideBar/index.js
> +import './style.scss';
move styles of this file into styles.scss

2021-11-20 16:07 UTC, meharajM commented on app/containers/Stories/index.js
> +        style={{
move to styles.scss

2021-11-20 16:24 UTC, shashankmotruri requested changes

2021-11-20 16:31 UTC, Ri5ha6h commented on app/containers/Dashboard/dummyStory.js
> +export const data = [
okay I'll delete it

2021-11-20 16:41 UTC, Ri5ha6h commented on server/controllers/google/google.js
>  };
it's all done by prettyfier plugin

2021-11-20 18:10 UTC, Ri5ha6h commented on app/containers/Dashboard/index.js
> +                            {stories[item].logLine}
yes they do have null checkers.

2021-11-21 07:32 UTC, Ri5ha6h commented on app/containers/Dashboard/dummyStory.js
> +];
it's done

2021-11-21 07:32 UTC, Ri5ha6h commented on app/containers/Profile/index.js
> +                style={{
it's done

2021-11-21 07:33 UTC, Ri5ha6h commented on app/containers/SideBar/index.js
> +import './style.scss';
done

2021-11-21 07:33 UTC, Ri5ha6h commented on app/containers/Stories/index.js
> +        style={{
done

2021-11-21 07:33 UTC, Ri5ha6h commented on app/containers/Dashboard/index.js
> +                              marginLeft: 5,
done

2021-11-21 07:33 UTC, Ri5ha6h commented on app/containers/Dashboard/index.js
> +                                    style={{
done

2021-11-21 07:33 UTC, Ri5ha6h commented on app/containers/Dashboard/index.js
> +                  style={{
done

2021-11-21 07:34 UTC, Ri5ha6h commented on app/containers/Dashboard/index.js
> +          style={{ border: 'none' }}
done

2021-11-21 07:34 UTC, Ri5ha6h commented on app/containers/Dashboard/index.js
> +            <span className="storySpan" style={{ fontSize: 18 }}>
done

2021-11-21 07:34 UTC, Ri5ha6h commented on app/containers/Dashboard/index.js
> +              style={{ fontSize: 20, marginLeft: 10 }}
done

2021-11-21 07:35 UTC, Ri5ha6h commented on app/containers/Dashboard/index.js
> +import './styles.scss';
done

2021-11-21 07:35 UTC, Ri5ha6h commented on app/containers/Dashboard/index.js
> +                      style={{
done

2021-11-22 05:35 UTC, shashankmotruri approved these changes

2021-11-22 05:36 UTC, merged