Feature/shashank/18 10 2021/mongoose
meharajM/mpp-v1 pull request #9
Opened 2021-11-04 17:51 UTC by shashankmotruri

2021-11-06 17:52 UTC, meharajM requested changes

2021-11-06 17:52 UTC, meharajM commented on app/containers/Logline/index.js
>      fetch(`/api/storyline/${this.state.updatedId}`, {
move it to utils as other APIs

2021-11-06 17:52 UTC, meharajM commented on server/controllers/google/Drivmodule.js
> +async function cReateFolder(tokens) {
change all the function names and variable names to appropriate camel Case

2021-11-06 17:52 UTC, meharajM commented on server/controllers/google/Oauthmodule.js
> +async function sToreToken(email,token) {
change functions name to camelcase

2021-11-06 17:52 UTC, meharajM commented on server/controllers/google/google.js
> +      responder(400)(err, null);
Create a list of all possible error scenarios in a doc so that we will go through and design handling of these errors in UI with custom status codes as messages

2021-11-06 17:52 UTC, meharajM commented on server/controllers/google/google.js
> +      responder(400)(err, null);
list out the scenarios in the same R & D doc which is shared with you

2021-11-06 17:52 UTC, meharajM commented on server/controllers/google/google.js
> +      responder(400)(err, null);
and create list of these scenarios for all the google api calls

2021-11-06 17:52 UTC, meharajM commented on server/controllers/google/google.js
>    const baseDir = path.join(__dirname, '../../storage/temp.json');
why are we updating the tokens in file, it is supposed to be stored and used from db only

2021-11-06 17:52 UTC, meharajM commented on server/controllers/google/google.js
> +    file_name = "story_line.json"
Add a task in trello for creating storyline with story_line_{totalStories.length + 1} file name if no title is given by user

2021-11-06 17:52 UTC, meharajM commented on server/controllers/google/google.js
> +  }
you could have just written `file_name = req.body.title.replace(/\s/g, '_')` in  line 245. that would work fine in all scenarios with if else

2021-11-06 17:52 UTC, meharajM commented on server/controllers/google/google.js
> +    console.log("Title is Null")
this whole block of can be written as `file_name  = req.body.title ? '${req.body.title.replace(/\s/g, '_') }.json': story_line.json `

2021-11-06 17:52 UTC, meharajM commented on server/controllers/google/google.js
> +
code from 278 to 288 is repeated in all google rated functions, put this in one function like getLatestToken() and call it in all places

2021-11-06 17:52 UTC, meharajM commented on server/controllers/google/google.js
> +      `https://www.googleapis.com/drive/v2/files/${driveIds.myp_fid}/children`, {
put it in google utils

2021-11-06 17:52 UTC, meharajM commented on server/controllers/login.js
> +      return res.status(404).send({msg: 'User does not exists'});
make a list of all these possible error scenarios as mentioned in comment earlier

2021-11-06 17:52 UTC, meharajM commented on server/utills/utills.js
> +    await fetch(`https://www.googleapis.com/oauth2/v3/tokeninfo?id_token=${token}`)
assign the identical part of the URI to a const and use it in all the places

2021-11-08 05:18 UTC, shashankmotruri commented on server/controllers/google/google.js
>    const baseDir = path.join(__dirname, '../../storage/temp.json');
these are not tokens , when file uploaded we are storing the data  temporarly

2021-11-08 12:24 UTC, shashankmotruri commented on server/controllers/google/google.js
> +
kept everything in validateAccess()

2021-11-08 15:50 UTC, meharajM requested changes

2021-11-08 15:50 UTC, meharajM commented on server/controllers/google/Drivmodule.js
> +async function cReateFolder(tokens) {
then name should be createFolder instead of cReateFolder

2021-11-08 15:50 UTC, meharajM commented on server/controllers/google/Drivmodule.js
> +async function sEndFile(res,fileMetadata, media,newTokens) {
sendFile instead of sEndFile

2021-11-08 15:50 UTC, meharajM commented on server/controllers/google/Drivmodule.js
> +async function iSfolderExist(tokens) {
isFolderExist instead of iSfloderExist

2021-11-08 16:02 UTC, meharajM requested changes

2021-11-08 16:02 UTC, meharajM commented on server/utills/utills.js
> +    default: fetch
Why are we making calls to the same endpoint https://www.googleapis.com/oauth2/v3/tokeninfo?id_token in 3 different functions, cant we use the one function only for all 3 places. it literally same API call written for 3 different purposes

2021-11-08 16:09 UTC, shashankmotruri commented on server/utills/utills.js
> +    default: fetch
No all 3 funcs are used for different ways
1st func  - verifyauthtoken is for middleware for all request
2nd func - its for getting email from the auth-token header
3rd func - its a custom func used in callback

2021-11-08 16:09 UTC, shashankmotruri commented on server/controllers/google/Drivmodule.js
> +async function iSfolderExist(tokens) {
changed

2021-11-08 16:09 UTC, shashankmotruri commented on server/controllers/google/Drivmodule.js
> +async function sEndFile(res,fileMetadata, media,newTokens) {
change

2021-11-08 16:56 UTC, meharajM approved these changes

2021-11-08 16:56 UTC, merged